### DISCUSSION TITLE
How to use docker `bde2020/spark-history-server` image?

### DISCUSSION THREAD

**Discussion by Giangblackk** [big-data-europe/docker-spark#156] [Q&A]
why do the `bde2020/spark-history-server` image configured with a local `/tmp/spark-events` directory for `spark.history.fs.logDirectory` instead of a HDFS folder or a shared volume?

When I tried to use this image, after submitting an example job, the History web page still can't show any job I submitted.
Here is my docker-compose file:
```
version: '3'

services:
  spark-master:
    image: bde2020/spark-master:3.2.0-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.2.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-history-server:
      image: bde2020/spark-history-server:3.2.0-hadoop3.2
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - "18081:18081"
      volumes:
       - spark-events:/tmp/spark-events

volumes:
  spark-events:
```
What did I do wrong?
Please advice.
Thanks.
