### ISSUE TITLE
connection issue between worker and master 

### ISSUE THREAD

**Issue by ashabbir** [big-data-europe/docker-spark#66]
when i start up my docker stack for spark
i get this exception most of the time

i am running docker stack in google cloud
10 machines cluster right now i cant even get one spark master worker to connect.
this is a random occurrence

i have three stack
1 - api (3 different service with 3 replica each proxied through trefik)
2 - pipeline (just to lunch pipeline in standalone client mode)
3 - spark (1 worker and 6 masters)

from spark worker docker i can ping the master 
PING master (10.0.23.55): 56 data bytes
64 bytes from 10.0.23.55: seq=0 ttl=64 time=0.114 ms
64 bytes from 10.0.23.55: seq=1 ttl=64 time=0.120 ms
64 bytes from 10.0.23.55: seq=2 ttl=64 time=0.116 ms
64 bytes from 10.0.23.55: seq=3 ttl=64 time=0.124 ms

stack.yml
```
version: '3.7'

networks:
  spark:
    name: spark
    attachable: true
  statsd:
    external: true
  hyperion-api_net_0:

x-deploy-template: &deploy-template
  placement:
    constraints:
      - node.role == worker


x-service-template: &service-template
  image: accern/hyperion:pipeline_${GIT_BRANCH:-master}
  env_file: ${HOME}/.env_settings/spark.env
  networks:
    - spark
    - statsd
    - hyperion-api_net_0

  logging:
    options:
      max-size: "500k"
  deploy:
    <<: *deploy-template

services:
  master:
    <<: *service-template
    image: accern/hyperion:spark_master_master
    environment:
      - ENABLE_INIT_DAEMON=false
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=master
      - SPARK_PUBLIC_DNS=xxx
    ports:
      - 8081:8080
      - 7077:7077
      - 4040:4040

  worker:
    <<: *service-template
    image: accern/hyperion:spark_worker_master
    environment:
      - "SPARK_MASTER=spark://master:7077"
      - ENABLE_INIT_DAEMON=false
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=xxx
    ports:
      - 8082:8082
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

```

2019-04-05 14:47:14 INFO  Worker:2566 - Started daemon with process name: 289@d2e88e21a245
2019-04-05 14:47:14 INFO  SignalUtils:54 - Registered signal handler for TERM
2019-04-05 14:47:14 INFO  SignalUtils:54 - Registered signal handler for HUP
2019-04-05 14:47:14 INFO  SignalUtils:54 - Registered signal handler for INT
2019-04-05 14:47:14 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-04-05 14:47:15 INFO  SecurityManager:54 - Changing view acls to: root
2019-04-05 14:47:15 INFO  SecurityManager:54 - Changing modify acls to: root
2019-04-05 14:47:15 INFO  SecurityManager:54 - Changing view acls groups to:
2019-04-05 14:47:15 INFO  SecurityManager:54 - Changing modify acls groups to:
2019-04-05 14:47:15 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
2019-04-05 14:47:15 INFO  Utils:54 - Successfully started service 'sparkWorker' on port 34297.
2019-04-05 14:47:15 INFO  Worker:54 - Starting Spark worker 10.0.23.60:34297 with 2 cores, 3.0 GB RAM
2019-04-05 14:47:15 INFO  Worker:54 - Running Spark version 2.4.0
2019-04-05 14:47:15 INFO  Worker:54 - Spark home: /spark
2019-04-05 14:47:15 INFO  log:192 - Logging initialized @2327ms
2019-04-05 14:47:16 INFO  Server:351 - jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
2019-04-05 14:47:16 INFO  Server:419 - Started @2398ms
2019-04-05 14:47:16 WARN  Utils:66 - Service 'WorkerUI' could not bind on port 8082. Attempting port 8083.
2019-04-05 14:47:16 INFO  AbstractConnector:278 - Started ServerConnector@23a72034{HTTP/1.1,[http/1.1]}{0.0.0.0:8083}
2019-04-05 14:47:16 INFO  Utils:54 - Successfully started service 'WorkerUI' on port 8083.
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7e8425b2{/logPage,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@17a461a7{/logPage/json,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@204a97bf{/,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@b73e6d{/json,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@342ace85{/static,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@6e2b5350{/log,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 INFO  WorkerWebUI:54 - Bound WorkerWebUI to 0.0.0.0, and started at http://xxxx:8083
2019-04-05 14:47:16 INFO  Worker:54 - Connecting to master master:7077...
2019-04-05 14:47:16 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@20c10f1d{/metrics/json,null,AVAILABLE,@Spark}
2019-04-05 14:47:16 WARN  Worker:87 - Failed to connect to master master:7077
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
	at org.apache.spark.deploy.worker.Worker$$anonfun$org$apache$spark$deploy$worker$Worker$$tryRegisterAllMasters$1$$anon$1.run(Worker.scala:253)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to connect to master/10.0.23.55:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	... 4 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: master/10.0.23.55:7077
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more
