### ISSUE TITLE
Connection refused when attempt to connect to Spark master in Swarm mode

### ISSUE THREAD

**Issue by hossein-kshvrz** [big-data-europe/docker-spark#80]
I want to run a python application on a Spark cluster, but my application is not inside the master container necessarily. The following is my compose yaml file:
```
version: '3'
services:
  spark-master:
    image: bde2020/spark-master
    deploy:
      placement:
        constraints:
          [node.hostname == master]
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - '6080:8080'
      - '6077:7077'
      - '6040:4040'
  spark-worker-1:
    image: bde2020/spark-worker
    depends_on:
      - 'spark-master'
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'
    ports:
      - '6081:8081'
      - '6041:4040'
```

When I create a stack and run these two containers on my Swarm cluster, and run my python application with the following SparkSession configuration, I receive `connection refused` error.

```
spark = SparkSession.builder \
    .master("spark://PRIVATE_HOST_IP:6077") \
    .appName("Spark Swarm") \
    .getOrCreate()
```
On the other hand when I run those containers in normal mode with `docker-compose up`, the same python application with the same SparkSession configuration works like a charm. Obviously, it is not desirable since I want to have the possibility of scaling up and down. Therefore I am looking for a way to run my application in Swarm mode.
